spring.data.mongodb.uri=mongodb://localhost:27017/kokobae_bakery

# JWT Configuration
jwt.secret=98d13ba082c01fc9bcae8b100365481ee147ca5bb235e0c8350b4cdaf74c8d5951594d09
jwt.expiration=86400000
# 24 hours in milliseconds

# CORS Configuration
spring.web.cors.allowed-origins=http://localhost:4200
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
